config/routes.rb
Rails.application.routes.draw do
  get '/', to: 'home#index'

  resources :restaurants, only: [:index, :show, :new, :create]

  resources :restaurants do
    resources :reviews, only: [:create, :new]
  end

end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
  validates_presence_of :name, :address, :city, :state, :zipcode

  has_many :reviews
end

app/models/review.rb
class Review < ActiveRecord::Base
  validates_presence_of :body, :rating

  belongs_to :restaurant

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def index
    @latest_restaurants = Restaurant.all.order("created_at asc").limit(10)
  end

end

app/controllers/restaurants_controller.rb
class RestaurantsController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def index
    @restaurants = Restaurant.all.order("name")
  end

  def show
    @r = Restaurant.find(params[:id])
    @reviews = @r.reviews
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)

    if @restaurant.save
      redirect_to restaurants_path
    else
      render :new
    end
  end

  def new
    @restaurant = Restaurant.new
  end

  private

  def restaurant_params
    # this method will return a hash like this:
    # { title: "whatever title", author: "some person", body: "blah blah blah" }
    params.require(:restaurant).permit(:name,:address,:city, :state, :zipcode,:description, :category)

  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception


  def create
    @review = Review.new(review_params)
    @review.restaurant_id = params[:restaurant_id]

    if @review.save
      redirect_to "/restaurants"
    else
      @restaurant = Restaurant.find(params[:restaurant_id])
      render :new
    end
  end

  def new
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new
  end

  private

  def review_params
    # this method will return a hash like this:
    # { title: "whatever title", author: "some person", body: "blah blah blah" }
    params.require(:review).permit(:rating,:body,:restaurant_id)

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
<ul>
<% @latest_restaurants.each do |r| %>
  <li><%= link_to r.name, restaurant_path(r) %></li>
<% end %>
<li></li>
<li><%= link_to "See All", restaurants_path %></li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GoodEats</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div id = "top_bar"><h1>Good Eats</h1></div>

<%= yield %>

</body>
</html>

app/views/restaurants/index.html.erb
<ul>
  <% @restaurants.each do |r| %>
    <li><%= link_to r.name, restaurant_path(r) %></li>
  <% end %>
</ul>

<p>Don't see one?<br>
  <%= link_to "Add your own", new_restaurant_path %>
</p>

app/views/restaurants/new.html.erb
<%= form_for @restaurant do |f| %>

    <%= f.label "Name" %>:
    <%= f.text_field :name %><br>

    <%= f.label "Address" %>:
    <%= f.text_field :address %>

    <%= f.label "City" %>:
    <%= f.text_field :city %>

    <%= f.label "State" %>:
    <%= f.text_field :state %>

    <%= f.label "Zip Code" %>:
    <%= f.text_field :zipcode %><br>

    <%= f.text_area :description,:rows => 10, :cols => 85, placeholder: "Description" %><br>

    <%= f.label "Category" %>:
    <%= f.text_field :category %>

    <%= f.submit %>
  <% end %>

app/views/restaurants/show.html.erb
<h1><%= @r.name %></h1>

<h3><%= @r.category %></h3>
<span><%= "#{@r.address}"%><br><%= "#{@r.city},#{@r.state} #{@r.zipcode}" %></span>

<h4>About</h4>
  <%= @r.description %>

<h4>Reviews</h4>
<ul>
  <% @reviews.each do |r| %>
    <li><b><%="#{r.rating}"%></b><em><%= " #{r.body}" %></em></li>
  <% end %>
</ul>

<%= link_to "Add your own", new_restaurant_review_path(@r) %>

app/views/reviews/new.html.erb
<%= form_for [@restaurant, @review] do |f| %>

    <%= f.label "Rating 1 - 5" %>:
    <%= f.number_field :rating, min: "0", max: "5"  %><br>

    <%= f.text_area :body, :rows => 10, :cols => 85, placeholder: "Add your review here" %>

    <%= f.submit %>
  <% end %>